"""
compare.py — Build outputs/comparison.md from baselines/ + outputs/.

Three engines per document:

  - VVA docs:        Unlimited-OCR | NuExtract 3 | Claude Sonnet 4.5 (baseline)
  - ASYOUWERE docs:  Unlimited-OCR | NuExtract 3 | docling           (baseline)

For each doc, writes a side-by-side stats table (chars, elapsed, pages,
notes) followed by 600-char excerpts so the diff is eyeballable without
running anything. Tolerant of missing engines — runs report what's present.

Run after unlimited_ocr_test.py / nuextract3_test.py have populated outputs/:
    uv run compare.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_MD = ROOT / "outputs" / "comparison.md"

BASELINE_ENGINES = {
    "vva": "claude-sonnet-4-5",
    "asyouwere": "docling",
}

# (display label, file suffix, location root)
ENGINE_LAYOUT = [
    ("Unlimited-OCR", "unlimited-ocr", "outputs"),
    ("NuExtract 3", "nuextract3", "outputs"),
    # baseline injected per-src below (different suffix per src)
]


def read_or_none(path: Path) -> str | None:
    return path.read_text(errors="replace") if path.exists() else None


def excerpt(text: str, n: int = 600) -> str:
    text = (text or "").strip()
    return text if len(text) <= n else text[:n].rstrip() + " …"


def engines_for(src: str) -> list[tuple[str, str, str]]:
    """Return list of (label, suffix, root) for this source."""
    engines = list(ENGINE_LAYOUT)
    baseline = BASELINE_ENGINES[src]
    engines.append((baseline, baseline, "baselines"))
    return engines


def load_engine(src: str, stem: str, suffix: str, root: str) -> tuple[str | None, dict]:
    txt = read_or_none(ROOT / root / src / f"{stem}.{suffix}.txt")
    meta_path = ROOT / root / src / f"{stem}.{suffix}.meta.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
    return txt, meta


def notes_for(label: str, meta: dict) -> str:
    bits: list[str] = []
    if "mode" in meta:
        bits.append(f"mode={meta['mode']}")
    if "dtype" in meta:
        bits.append(f"dtype={meta['dtype']}")
    if meta.get("est_cost_usd"):
        bits.append(f"~${meta['est_cost_usd']}")
    if "model" in meta and meta["model"] not in label:
        bits.append(meta["model"].split("/")[-1])
    return ", ".join(bits) if bits else "—"


def doc_block(src: str, stem: str) -> str:
    engines = engines_for(src)
    rows: list[tuple[str, str | None, dict]] = []
    for label, suffix, root in engines:
        txt, meta = load_engine(src, stem, suffix, root)
        rows.append((label, txt, meta))

    lines: list[str] = [f"### `{src}/{stem}.pdf`\n"]
    lines.append("| Engine | chars | elapsed (s) | pages | notes |")
    lines.append("|---|---:|---:|---:|---|")
    for label, txt, meta in rows:
        char_count = meta.get("char_count", len(txt) if txt else "—")
        lines.append(
            f"| **{label}** | {char_count} "
            f"| {meta.get('elapsed_s', '—')} "
            f"| {meta.get('n_pages', '—')} "
            f"| {notes_for(label, meta)} |"
        )
    lines.append("")

    for label, txt, _meta in rows:
        lines.append(f"<details><summary>{label} excerpt</summary>\n")
        lines.append("```")
        lines.append(excerpt(txt or "(no output yet — run the matching script)"))
        lines.append("```\n</details>\n")

    return "\n".join(lines)


def main() -> int:
    docs: list[tuple[str, str]] = []
    for src in ("vva", "asyouwere"):
        for pdf in sorted((ROOT / "docs" / src).glob("*.pdf")):
            docs.append((src, pdf.stem))

    out: list[str] = [
        "# OCR comparison — Unlimited-OCR vs NuExtract 3 vs prior baselines\n",
        "Auto-generated by `compare.py`. Each doc shows a side-by-side stats "
        "table and the first ~600 chars of each engine's output for fast "
        "visual diffing.\n",
    ]

    for src, stem in docs:
        out.append(doc_block(src, stem))
        out.append("---\n")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(out))
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
