"""
compare.py — Build outputs/comparison.md from baselines/ + outputs/.

Reads each pair of (Unlimited-OCR output, baseline output) and writes a
single markdown file with:

  - per-doc table of char_count + elapsed_s for each engine
  - side-by-side excerpts (first ~600 chars) so a reader can eyeball
    quality without running anything

Engines compared:
  - VVA docs:        Unlimited-OCR vs Claude Sonnet 4.5 vision
  - ASYOUWERE docs:  Unlimited-OCR vs docling

Run after unlimited_ocr_test.py has populated outputs/:
    uv run compare.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_MD = ROOT / "outputs" / "comparison.md"

BASELINE_ENGINES = {
    "vva": "claude-sonnet-4-5",
    "asyouwere": "docling",
}


def read_or_none(path: Path) -> str | None:
    return path.read_text(errors="replace") if path.exists() else None


def excerpt(text: str, n: int = 600) -> str:
    text = (text or "").strip()
    return text if len(text) <= n else text[:n].rstrip() + " …"


def doc_block(src: str, stem: str) -> str:
    baseline_eng = BASELINE_ENGINES[src]
    u_txt = read_or_none(ROOT / "outputs" / src / f"{stem}.unlimited-ocr.txt")
    u_meta_path = ROOT / "outputs" / src / f"{stem}.unlimited-ocr.meta.json"
    u_meta = json.loads(u_meta_path.read_text()) if u_meta_path.exists() else {}

    b_txt = read_or_none(ROOT / "baselines" / src / f"{stem}.{baseline_eng}.txt")
    b_meta_path = ROOT / "baselines" / src / f"{stem}.{baseline_eng}.meta.json"
    b_meta = json.loads(b_meta_path.read_text()) if b_meta_path.exists() else {}

    lines: list[str] = []
    lines.append(f"### `{src}/{stem}.pdf`\n")

    lines.append("| Engine | chars | elapsed (s) | pages | notes |")
    lines.append("|---|---:|---:|---:|---|")
    lines.append(
        f"| **Unlimited-OCR** | {u_meta.get('char_count', '—')} "
        f"| {u_meta.get('elapsed_s', '—')} "
        f"| {u_meta.get('n_pages', '—')} "
        f"| mode={u_meta.get('mode', '—')} |"
    )
    lines.append(
        f"| {baseline_eng} | {b_meta.get('char_count', len(b_txt) if b_txt else '—')} "
        f"| {b_meta.get('elapsed_s', '—')} "
        f"| {b_meta.get('n_pages', '—')} "
        f"| {'cost ≈ $' + str(b_meta.get('est_cost_usd')) if b_meta.get('est_cost_usd') else '—'} |"
    )
    lines.append("")

    lines.append(f"<details><summary>Unlimited-OCR excerpt</summary>\n")
    lines.append("```")
    lines.append(excerpt(u_txt or "(no output yet — run unlimited_ocr_test.py first)"))
    lines.append("```\n</details>\n")

    lines.append(f"<details><summary>{baseline_eng} excerpt</summary>\n")
    lines.append("```")
    lines.append(excerpt(b_txt or "(no baseline file)"))
    lines.append("```\n</details>\n")

    return "\n".join(lines)


def main() -> int:
    docs: list[tuple[str, str]] = []
    for src in ("vva", "asyouwere"):
        for pdf in sorted((ROOT / "docs" / src).glob("*.pdf")):
            docs.append((src, pdf.stem))

    out: list[str] = []
    out.append("# OCR comparison — Unlimited-OCR vs prior baselines\n")
    out.append(
        "Auto-generated by `compare.py`. Each doc shows side-by-side stats and "
        "the first ~600 chars of each engine's output for fast visual diffing."
    )
    out.append("")

    for src, stem in docs:
        out.append(doc_block(src, stem))
        out.append("---\n")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(out))
    print(f"Wrote {OUT_MD.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
